model:
  base_learning_rate: 1.0e-4   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: "image"
    image_size: 8
    channels: 3
    scale_by_std: True
    monitor: 'val/loss_simple_ema'
    use_ema: True
    save_statistics: True
    

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 8
        in_channels: 3
        out_channels: 3
        model_channels: 128
        attention_resolutions: [ 8, 4, 2 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,4 ]  # 32, 16, 8, 4, 2
        num_head_channels: 64
        use_checkpoint: False
        legacy: False
        
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: "logs/2025-09-06T19-02-37_autoencoder_kl_8x8x6/checkpoints/epoch=000359.ckpt"
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 32
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 4
    wrap: False
    train:
      target: ldm.data.cifar10.CIFAR10Train
      params:
        size: 32
    validation:
      target: ldm.data.cifar10.CIFAR10Validation
      params:
        size: 32

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    gradient_clip_val: 1  